version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Replace with a supported Node.js version
    commands:
      - npm install

  build:
    commands:
      - node app.js

artifacts:
  files:
    - '**/*' # Include all files in the project directory
  discard-paths: yes

cache:
  paths:
    - node_modules/
